
from catalogo import Catalogo

catalogo_biblioteca = Catalogo()

# ======================= A =======================
catalogo_biblioteca.addLivro("A Revolução dos Bichos", "George Orwell", "1945", "Companhia das Letras", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("A Menina que Roubava Livros", "Markus Zusak", "2005", "Intrínseca", "Rio de Janeiro", "5", "Emprestado")
catalogo_biblioteca.addLivro("A Culpa é das Estrelas", "John Green", "2012", "Intrínseca", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("A Cabana", "William P. Young", "2007", "Arqueiro", "São Paulo", "2", "Emprestado")
catalogo_biblioteca.addLivro("A Guerra dos Tronos", "George R. R. Martin", "1996", "LeYa", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("A Hora da Estrela", "Clarice Lispector", "1977", "Rocco", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("A Moreninha", "Joaquim Manuel de Macedo", "1844", "Melhoramentos", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("A Metamorfose", "Franz Kafka", "1915", "Antofágica", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("A Divina Comédia", "Dante Alighieri", "1320", "Editora 34", "São Paulo", "2", "Emprestado")
catalogo_biblioteca.addLivro("A Senhora", "José de Alencar", "1875", "Martin Claret", "São Paulo", "6", "Disponível")

# ======================= B =======================
catalogo_biblioteca.addLivro("Biblia Sagrada", "Diversos autores", "século I", "SBB", "São Paulo", "10", "Disponível")
catalogo_biblioteca.addLivro("Boneco de Neve", "Jo Nesbø", "2007", "Record", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("Box Harry Potter", "J.K. Rowling", "1997", "Rocco", "Rio de Janeiro", "8", "Disponível")
catalogo_biblioteca.addLivro("Battle Royale", "Koushun Takami", "1999", "Globo Livros", "São Paulo", "4", "Emprestado")
catalogo_biblioteca.addLivro("Brida", "Paulo Coelho", "1990", "Paralela", "São Paulo", "6", "Disponível")
catalogo_biblioteca.addLivro("Budapeste", "Chico Buarque", "2003", "Companhia das Letras", "São Paulo", "2", "Emprestado")
catalogo_biblioteca.addLivro("Boa Noite Punpun", "Inio Asano", "2007", "Panini", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Box O Senhor dos Anéis", "J.R.R. Tolkien", "1954", "Martins Fontes", "São Paulo", "7", "Disponível")
catalogo_biblioteca.addLivro("Brás Cubas", "Machado de Assis", "1881", "Antofágica", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("Box Percy Jackson", "Rick Riordan", "2005", "Intrínseca", "Rio de Janeiro", "6", "Disponível")

# ======================= C =======================
catalogo_biblioteca.addLivro("Cem Anos de Solidão", "Gabriel García Márquez", "1967", "Record", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Cidades de Papel", "John Green", "2008", "Intrínseca", "Rio de Janeiro", "5", "Emprestado")
catalogo_biblioteca.addLivro("Contos de Fadas", "Hans Christian Andersen", "1837", "Zahar", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Coraline", "Neil Gaiman", "2002", "Rocco", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Corte de Espinhos e Rosas", "Sarah J. Maas", "2015", "Galera Record", "Rio de Janeiro", "5", "Emprestado")
catalogo_biblioteca.addLivro("Comédias da Vida Privada", "Luis Fernando Verissimo", "1994", "Objetiva", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Crime e Castigo", "Fiódor Dostoiévski", "1866", "Principis", "São Paulo", "6", "Emprestado")
catalogo_biblioteca.addLivro("Coração das Trevas", "Joseph Conrad", "1899", "Antofágica", "São Paulo", "2", "Disponível")
catalogo_biblioteca.addLivro("Cinderela", "Charles Perrault", "1697", "Zahar", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Caim", "José Saramago", "2009", "Companhia das Letras", "São Paulo", "4", "Emprestado")

# ======================= D =======================
catalogo_biblioteca.addLivro("Dom Casmurro", "Machado de Assis", "1899", "Antofágica", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Diário de um Banana", "Jeff Kinney", "2007", "VR Editora", "São Paulo", "7", "Emprestado")
catalogo_biblioteca.addLivro("Duna", "Frank Herbert", "1965", "Aleph", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Drácula", "Bram Stoker", "1897", "Zahar", "Rio de Janeiro", "4", "Emprestado")
catalogo_biblioteca.addLivro("Desventuras em Série", "Lemony Snicket", "1999", "Companhia das Letras", "São Paulo", "6", "Disponível")
catalogo_biblioteca.addLivro("Diário de Anne Frank", "Anne Frank", "1947", "Record", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Dom Quixote", "Miguel de Cervantes", "1605", "Principis", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("De Volta ao Mundo em 80 Dias", "Júlio Verne", "1872", "Zahar", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Deuses Americanos", "Neil Gaiman", "2001", "Intrínseca", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("Depois do Fim", "Daniel Bovolento", "2017", "Benvirá", "São Paulo", "2", "Disponível")

# ======================= E =======================
catalogo_biblioteca.addLivro("Eu, Robô", "Isaac Asimov", "1950", "Aleph", "São Paulo", "6", "Disponível")
catalogo_biblioteca.addLivro("Eragon", "Christopher Paolini", "2003", "Rocco", "Rio de Janeiro", "5", "Emprestado")
catalogo_biblioteca.addLivro("Eleanor & Park", "Rainbow Rowell", "2013", "Novo Século", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("E o Vento Levou", "Margaret Mitchell", "1936", "Record", "Rio de Janeiro", "4", "Emprestado")
catalogo_biblioteca.addLivro("Extraordinário", "R. J. Palacio", "2012", "Intrínseca", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Ensaio sobre a Cegueira", "José Saramago", "1995", "Companhia das Letras", "São Paulo", "4", "Emprestado")
catalogo_biblioteca.addLivro("Ecos", "Pam Muñoz Ryan", "2015", "DarkSide Books", "Rio de Janeiro", "2", "Disponível")
catalogo_biblioteca.addLivro("Entre Linhas", "Jennifer Roy", "2007", "Rocco", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("Eu Sou Malala", "Malala Yousafzai", "2013", "Companhia das Letras", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Eleanor Oliphant Está Muito Bem", "Gail Honeyman", "2017", "Intrínseca", "Rio de Janeiro", "2", "Emprestado")

# ======================= F =======================
catalogo_biblioteca.addLivro("Fahrenheit 451", "Ray Bradbury", "1953", "Biblioteca Azul", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Fragmentos do Horror", "Junji Ito", "2014", "DarkSide Books", "Rio de Janeiro", "4", "Emprestado")
catalogo_biblioteca.addLivro("Feliz Ano Velho", "Marcelo Rubens Paiva", "1982", "Alfaguara", "São Paulo", "6", "Disponível")
catalogo_biblioteca.addLivro("Frankenstein", "Mary Shelley", "1818", "Zahar", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Filhos do Éden", "Eduardo Spohr", "2011", "Verus", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("Fogo e Sangue", "George R. R. Martin", "2018", "Suma", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Feios", "Scott Westerfeld", "2005", "Galera Record", "Rio de Janeiro", "2", "Emprestado")
catalogo_biblioteca.addLivro("Fundação", "Isaac Asimov", "1951", "Aleph", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Flores para Algernon", "Daniel Keyes", "1966", "Aleph", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Felicidade Clandestina", "Clarice Lispector", "1971", "Rocco", "Rio de Janeiro", "2", "Emprestado")

# ======================= G =======================
catalogo_biblioteca.addLivro("Guerra e Paz", "Liev Tolstói", "1869", "Penguin-Companhia", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Gente Humilde", "Machado de Assis", "1890", "Antofágica", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("Gente que Vai e Volta", "Martha Medeiros", "2005", "Arx", "Porto Alegre", "5", "Disponível")
catalogo_biblioteca.addLivro("Garota Exemplar", "Gillian Flynn", "2012", "Intrínseca", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Game of Thrones", "George R. R. Martin", "1996", "LeYa", "Rio de Janeiro", "6", "Emprestado")
catalogo_biblioteca.addLivro("Guia do Mochileiro das Galáxias", "Douglas Adams", "1979", "Arqueiro", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Grande Sertão: Veredas", "João Guimarães Rosa", "1956", "José Olympio", "Rio de Janeiro", "5", "Emprestado")
catalogo_biblioteca.addLivro("Guerra dos Tronos", "George R. R. Martin", "1996", "LeYa", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Garota no Trem", "Paula Hawkins", "2015", "Intrínseca", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("Gigantes de Aço", "Bernard Cornwell", "2001", "Record", "Rio de Janeiro", "2", "Disponível")

# ======================= H =======================
catalogo_biblioteca.addLivro("Harry Potter e a Pedra Filosofal", "J.K. Rowling", "1997", "Rocco", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Harry Potter e a Câmara Secreta", "J.K. Rowling", "1998", "Rocco", "Rio de Janeiro", "5", "Emprestado")
catalogo_biblioteca.addLivro("Harry Potter e o Prisioneiro de Azkaban", "J.K. Rowling", "1999", "Rocco", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Harry Potter e o Cálice de Fogo", "J.K. Rowling", "2000", "Rocco", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("Harry Potter e a Ordem da Fênix", "J.K. Rowling", "2003", "Rocco", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Harry Potter e o Enigma do Príncipe", "J.K. Rowling", "2005", "Rocco", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Harry Potter e as Relíquias da Morte", "J.K. Rowling", "2007", "Rocco", "Rio de Janeiro", "5", "Emprestado")
catalogo_biblioteca.addLivro("Hobbit", "J.R.R. Tolkien", "1937", "Martins Fontes", "São Paulo", "6", "Disponível")
catalogo_biblioteca.addLivro("História Sem Fim", "Michael Ende", "1979", "Rocco", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("Hunger Games", "Suzanne Collins", "2008", "Rocco", "Rio de Janeiro", "4", "Disponível")

# ======================= I =======================
catalogo_biblioteca.addLivro("It: A Coisa", "Stephen King", "1986", "Suma de Letras", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Inferno", "Dan Brown", "2013", "Arqueiro", "São Paulo", "4", "Emprestado")
catalogo_biblioteca.addLivro("Ilíada", "Homero", "século VIII a.C.", "Zahar", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Indomável", "Kate McCarthy", "2018", "Intrínseca", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Intensamente", "Elaine V. B. Carvalho", "2017", "Globo Livros", "Rio de Janeiro", "2", "Emprestado")
catalogo_biblioteca.addLivro("Imaginação em Foco", "Isabel Allende", "1998", "Objetiva", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Iracema", "José de Alencar", "1865", "Martin Claret", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Isolados", "Stephanie Kuehn", "2019", "Intrínseca", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("Inimigos Públicos", "Tracy Kidder", "2006", "Companhia das Letras", "São Paulo", "2", "Disponível")
catalogo_biblioteca.addLivro("Invenções e Descobertas", "Isaac Asimov", "1963", "Aleph", "São Paulo", "5", "Emprestado")

# ======================= J =======================
catalogo_biblioteca.addLivro("Jogos Vorazes", "Suzanne Collins", "2008", "Rocco", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Jane Eyre", "Charlotte Brontë", "1847", "Zahar", "Rio de Janeiro", "4", "Emprestado")
catalogo_biblioteca.addLivro("Jardim Secreto", "Frances Hodgson Burnett", "1911", "Rocco", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("João e Maria", "Irmãos Grimm", "1812", "Zahar", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Jubiabá", "Jorge Amado", "1935", "Companhia das Letras", "São Paulo", "4", "Emprestado")
catalogo_biblioteca.addLivro("Justiça", "Michael Connelly", "2006", "Suma de Letras", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Jovens, Loucos e Rebeldes", "Michael Zadoorian", "2010", "Rocco", "Rio de Janeiro", "2", "Emprestado")
catalogo_biblioteca.addLivro("Jurassic Park", "Michael Crichton", "1990", "Aleph", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Jogos de Adultos", "Lisa Jewell", "2019", "Intrínseca", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("Jornal de um Detetive", "Agatha Christie", "1920", "Martins Fontes", "São Paulo", "5", "Disponível")

# ======================= K =======================
catalogo_biblioteca.addLivro("Kane & Abel", "Jeffrey Archer", "1979", "Record", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Kafka à Beira-Mar", "Haruki Murakami", "2002", "Alfaguara", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("Kiki's Delivery Service", "Eiko Kadono", "1985", "Rocco", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Kingdom Come", "Mark Waid", "1996", "Panini", "São Paulo", "2", "Emprestado")
catalogo_biblioteca.addLivro("Killing Floor", "Lee Child", "1997", "Arqueiro", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Kagemusha", "Akira Kurosawa", "1980", "Record", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("K-PAX", "Gene Brewer", "1985", "Suma de Letras", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Keepers", "Ted Dekker", "2005", "Benvirá", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("King Lear", "William Shakespeare", "1606", "Zahar", "Rio de Janeiro", "2", "Emprestado")
catalogo_biblioteca.addLivro("Kiss the Girls", "James Patterson", "1995", "Record", "Rio de Janeiro", "3", "Disponível")

# ======================= L =======================
catalogo_biblioteca.addLivro("Lord of the Rings: A Sociedade do Anel", "J.R.R. Tolkien", "1954", "Martins Fontes", "São Paulo", "6", "Disponível")
catalogo_biblioteca.addLivro("Lord of the Rings: As Duas Torres", "J.R.R. Tolkien", "1954", "Martins Fontes", "São Paulo", "5", "Emprestado")
catalogo_biblioteca.addLivro("Lord of the Rings: O Retorno do Rei", "J.R.R. Tolkien", "1955", "Martins Fontes", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Laranja Mecânica", "Anthony Burgess", "1962", "Companhia das Letras", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("Laços", "Luiz Antonio Aguiar", "2011", "Rocco", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Ladainha", "José Mauro de Vasconcelos", "1971", "Rocco", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Livro dos Espíritos", "Allan Kardec", "1857", "FEB", "São Paulo", "6", "Emprestado")
catalogo_biblioteca.addLivro("Língua de Trapos", "Luiz Puntel", "1995", "Zahar", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Luzes de Emergência", "José Saramago", "2008", "Companhia das Letras", "São Paulo", "4", "Emprestado")
catalogo_biblioteca.addLivro("Lobo da Estepe", "Hermann Hesse", "1927", "Martins Fontes", "São Paulo", "2", "Disponível")

# ======================= M =======================
catalogo_biblioteca.addLivro("Memórias Póstumas de Brás Cubas", "Machado de Assis", "1881", "Antofágica", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Moby Dick", "Herman Melville", "1851", "Martins Fontes", "São Paulo", "4", "Emprestado")
catalogo_biblioteca.addLivro("Mais Esperto que o Diabo", "Napoleon Hill", "1938", "Suma de Letras", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Mulherzinhas", "Louisa May Alcott", "1868", "Zahar", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Meu Pé de Laranja Lima", "José Mauro de Vasconcelos", "1968", "Rocco", "Rio de Janeiro", "6", "Emprestado")
catalogo_biblioteca.addLivro("Milagre na Cela 7", "Celeste Ng", "2016", "Intrínseca", "Rio de Janeiro", "2", "Disponível")
catalogo_biblioteca.addLivro("Matadouro Cinco", "Kurt Vonnegut", "1969", "Companhia das Letras", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Mulheres que Correm com os Lobos", "Clarissa Pinkola Estés", "1992", "Rocco", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("Mistborn: O Império Final", "Brandon Sanderson", "2006", "Suma", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Minha Vida de Menina", "Helena Morley", "1942", "Martins Fontes", "São Paulo", "4", "Emprestado")

# ======================= N =======================
catalogo_biblioteca.addLivro("Nunca Me Deixe", "Kazuo Ishiguro", "2005", "Companhia das Letras", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Nosso Lar", "Chico Xavier", "1944", "FEB", "São Paulo", "4", "Emprestado")
catalogo_biblioteca.addLivro("Neuromancer", "William Gibson", "1984", "Aleph", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Nome da Rosa", "Umberto Eco", "1980", "Record", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Na Natureza Selvagem", "Jon Krakauer", "1996", "Intrínseca", "Rio de Janeiro", "2", "Emprestado")
catalogo_biblioteca.addLivro("Nineteen Eighty-Four", "George Orwell", "1949", "Companhia das Letras", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Náufrago", "Richard Bach", "1970", "Zahar", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Novas Cartas Portuguesas", "Maria Isabel Barreno", "1972", "Martins Fontes", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("Nunca Fui sua Mulher", "Marcelo Rubens Paiva", "2013", "Record", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Nomes Provisórios", "José Eduardo Agualusa", "2008", "Companhia das Letras", "São Paulo", "2", "Emprestado")

# ======================= O =======================
catalogo_biblioteca.addLivro("O Pequeno Príncipe", "Antoine de Saint-Exupéry", "1943", "Agir", "São Paulo", "6", "Disponível")
catalogo_biblioteca.addLivro("O Senhor dos Anéis: A Sociedade do Anel", "J.R.R. Tolkien", "1954", "Martins Fontes", "São Paulo", "5", "Emprestado")
catalogo_biblioteca.addLivro("O Senhor dos Anéis: As Duas Torres", "J.R.R. Tolkien", "1954", "Martins Fontes", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("O Senhor dos Anéis: O Retorno do Rei", "J.R.R. Tolkien", "1955", "Martins Fontes", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("O Alquimista", "Paulo Coelho", "1988", "Paralela", "São Paulo", "6", "Disponível")
catalogo_biblioteca.addLivro("O Cortiço", "Aluísio Azevedo", "1890", "Martin Claret", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("O Hobbit", "J.R.R. Tolkien", "1937", "Martins Fontes", "São Paulo", "5", "Emprestado")
catalogo_biblioteca.addLivro("O Escaravelho do Diabo", "Lúcia Machado de Almeida", "1953", "Ática", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("O Processo", "Franz Kafka", "1925", "Antofágica", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("O Retrato de Dorian Gray", "Oscar Wilde", "1890", "Zahar", "Rio de Janeiro", "2", "Emprestado")

# ======================= P =======================
catalogo_biblioteca.addLivro("Percy Jackson e o Ladrão de Raios", "Rick Riordan", "2005", "Intrínseca", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Percy Jackson e o Mar de Monstros", "Rick Riordan", "2006", "Intrínseca", "Rio de Janeiro", "5", "Emprestado")
catalogo_biblioteca.addLivro("Percy Jackson e a Maldição do Titã", "Rick Riordan", "2007", "Intrínseca", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Percy Jackson e a Batalha do Labirinto", "Rick Riordan", "2008", "Intrínseca", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("Percy Jackson e o Último Olimpiano", "Rick Riordan", "2009", "Intrínseca", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Pequenas Grandes Mentiras", "Liane Moriarty", "2014", "Arqueiro", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Peter Pan", "J.M. Barrie", "1911", "Zahar", "Rio de Janeiro", "5", "Emprestado")
catalogo_biblioteca.addLivro("Planeta dos Macacos", "Pierre Boulle", "1963", "Rocco", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Poderoso Chefão", "Mario Puzo", "1969", "Zahar", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Pássaros Feridos", "Colleen McCullough", "1977", "Record", "Rio de Janeiro", "2", "Emprestado")

# ======================= Q =======================
catalogo_biblioteca.addLivro("Quincas Borba", "Machado de Assis", "1891", "Antofágica", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Querido John", "Nicholas Sparks", "2007", "Arqueiro", "São Paulo", "4", "Emprestado")
catalogo_biblioteca.addLivro("Questões do Coração", "Julia Quinn", "2008", "Arqueiro", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Quadribol Através dos Séculos", "Kennilworthy Whisp", "2001", "Rocco", "Rio de Janeiro", "2", "Emprestado")
catalogo_biblioteca.addLivro("Queda de Gigantes", "Ken Follett", "2010", "Record", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Quatro Vidas de um Cachorro", "W. Bruce Cameron", "2010", "Novo Conceito", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Quase Uma Rockstar", "Julia Quinn", "2012", "Arqueiro", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("Quatro Amigas e um Jeans Viajante", "Ann Brashares", "2001", "Rocco", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Quem é Você, Alasca?", "John Green", "2005", "Intrínseca", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Quero Ser Beth Levitt", "Elizabeth Gilbert", "2009", "Record", "Rio de Janeiro", "2", "Emprestado")
# ======================= R =======================
catalogo_biblioteca.addLivro("Romeu e Julieta", "William Shakespeare", "1597", "Martin Claret", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Robinson Crusoé", "Daniel Defoe", "1719", "Zahar", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Riqueza e Pobreza", "John Kenneth Galbraith", "1958", "Companhia das Letras", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("Rastro de Sangue", "James Patterson", "2006", "Arqueiro", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Revolução dos Bichos", "George Orwell", "1945", "Companhia das Letras", "São Paulo", "6", "Disponível")
catalogo_biblioteca.addLivro("Refúgio Secreto", "Nicholas Sparks", "2011", "Arqueiro", "Rio de Janeiro", "4", "Emprestado")
catalogo_biblioteca.addLivro("Rodas da Vida", "Elisabeth Kübler-Ross", "1987", "Rocco", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Raízes", "Alex Haley", "1976", "Zahar", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Rebeldes", "S.E. Hinton", "1967", "Record", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Romance de Três", "Jean Webster", "1912", "Martins Fontes", "São Paulo", "4", "Emprestado")

# ======================= S =======================
catalogo_biblioteca.addLivro("Senhor das Moscas", "William Golding", "1954", "Zahar", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Sherlock Holmes: Um Estudo em Vermelho", "Arthur Conan Doyle", "1887", "Martins Fontes", "São Paulo", "4", "Emprestado")
catalogo_biblioteca.addLivro("Sapiens: Uma Breve História da Humanidade", "Yuval Noah Harari", "2011", "L&PM", "Porto Alegre", "6", "Disponível")
catalogo_biblioteca.addLivro("Sexta-Feira, 13", "Christopher Pike", "1985", "Globo Livros", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Saga Crepúsculo: Amanhecer", "Stephenie Meyer", "2008", "Intrínseca", "Rio de Janeiro", "4", "Emprestado")
catalogo_biblioteca.addLivro("Saga Crepúsculo: Eclipse", "Stephenie Meyer", "2007", "Intrínseca", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Saga Crepúsculo: Lua Nova", "Stephenie Meyer", "2006", "Intrínseca", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Saga Crepúsculo: Crepúsculo", "Stephenie Meyer", "2005", "Intrínseca", "Rio de Janeiro", "4", "Emprestado")
catalogo_biblioteca.addLivro("Sangue do Olimpo", "Rick Riordan", "2014", "Intrínseca", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Senhor dos Anéis: A Sociedade do Anel", "J.R.R. Tolkien", "1954", "Martins Fontes", "São Paulo", "5", "Emprestado")

# ======================= T =======================
catalogo_biblioteca.addLivro("Trono de Vidro", "Sarah J. Maas", "2012", "Galera Record", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Trilogia Millennium: Os Homens que Não Amavam as Mulheres", "Stieg Larsson", "2005", "Companhia das Letras", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("Trilogia Millennium: A Menina que Brincava com Fogo", "Stieg Larsson", "2006", "Companhia das Letras", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Trilogia Millennium: A Rainha do Castelo de Ar", "Stieg Larsson", "2007", "Companhia das Letras", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Toda Luz que Não Podemos Ver", "Anthony Doerr", "2014", "Arqueiro", "São Paulo", "6", "Emprestado")
catalogo_biblioteca.addLivro("Tartarugas Até Lá Embaixo", "John Green", "2017", "Intrínseca", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Tempos de Guerra", "Ken Follett", "2013", "Record", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Teorema do Papagaio", "Denis Guedj", "1998", "Rocco", "Rio de Janeiro", "2", "Emprestado")
catalogo_biblioteca.addLivro("Terror na Colina", "R.L. Stine", "1992", "Globo Livros", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Três Homens em um Barco", "Jerome K. Jerome", "1889", "Zahar", "Rio de Janeiro", "4", "Emprestado")

# ======================= U =======================
catalogo_biblioteca.addLivro("Um Conto de Duas Cidades", "Charles Dickens", "1859", "Zahar", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Um Estudo em Vermelho", "Arthur Conan Doyle", "1887", "Martins Fontes", "São Paulo", "4", "Emprestado")
catalogo_biblioteca.addLivro("Um Lugar Chamado Notting Hill", "Richard Curtis", "1999", "Globo Livros", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Um Olhar do Paraíso", "Alice Sebold", "2002", "Record", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Um Conto de Natal", "Charles Dickens", "1843", "Zahar", "Rio de Janeiro", "2", "Emprestado")
catalogo_biblioteca.addLivro("Uma Breve História do Tempo", "Stephen Hawking", "1988", "Cristal", "São Paulo", "6", "Disponível")
catalogo_biblioteca.addLivro("Um Amor para Recordar", "Nicholas Sparks", "1999", "Arqueiro", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Um Dia", "David Nicholls", "2009", "Arqueiro", "São Paulo", "4", "Emprestado")
catalogo_biblioteca.addLivro("Um Homem de Sorte", "Nicholas Sparks", "2007", "Arqueiro", "São Paulo", "2", "Disponível")
catalogo_biblioteca.addLivro("Um Mundo Feliz", "Aldous Huxley", "1932", "Companhia das Letras", "São Paulo", "5", "Emprestado")

# ======================= V =======================
catalogo_biblioteca.addLivro("Vinte Mil Léguas Submarinas", "Júlio Verne", "1870", "Zahar", "Rio de Janeiro", "6", "Disponível")
catalogo_biblioteca.addLivro("Vidas Secas", "Graciliano Ramos", "1938", "José Olympio", "Rio de Janeiro", "4", "Emprestado")
catalogo_biblioteca.addLivro("Vampiros do Rio", "Bruno de Oliveira", "2011", "Rocco", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Vingança", "James Patterson", "2002", "Arqueiro", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Veronika Decide Morrer", "Paulo Coelho", "1998", "Paralela", "São Paulo", "5", "Emprestado")
catalogo_biblioteca.addLivro("Vento, Areia e Estrelas", "Antoine de Saint-Exupéry", "1939", "Agir", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Vingadores: Guerra Infinita", "Stan Lee", "2018", "Panini", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Vida", "Stephenie Meyer", "2020", "Intrínseca", "Rio de Janeiro", "2", "Emprestado")
catalogo_biblioteca.addLivro("Velocidade Máxima", "Dan Brown", "2000", "Arqueiro", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Vingadores: Era de Ultron", "Stan Lee", "2015", "Panini", "São Paulo", "3", "Emprestado")

# ======================= W =======================
catalogo_biblioteca.addLivro("Wicked: A Vida e as Mentiras da Bruxa Má", "Gregory Maguire", "1995", "Rocco", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Wuthering Heights", "Emily Brontë", "1847", "Zahar", "Rio de Janeiro", "4", "Emprestado")
catalogo_biblioteca.addLivro("Watchmen", "Alan Moore", "1987", "Panini", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Wolf Hall", "Hilary Mantel", "2009", "Intrínseca", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("War and Peace", "Leo Tolstoy", "1869", "Penguin-Companhia", "São Paulo", "6", "Emprestado")
catalogo_biblioteca.addLivro("Where the Crawdads Sing", "Delia Owens", "2018", "Arqueiro", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("World War Z", "Max Brooks", "2006", "Suma de Letras", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Watership Down", "Richard Adams", "1972", "Rocco", "Rio de Janeiro", "4", "Emprestado")
catalogo_biblioteca.addLivro("Wicked Lovely", "Melissa Marr", "2007", "Galera Record", "Rio de Janeiro", "2", "Disponível")
catalogo_biblioteca.addLivro("White Teeth", "Zadie Smith", "2000", "Record", "Rio de Janeiro", "3", "Emprestado")
# ======================= X =======================
catalogo_biblioteca.addLivro("X-Men: Dias de um Futuro Esquecido", "Chris Claremont", "1981", "Panini", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Xingu", "Antonio Callado", "1967", "Record", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Xerxes", "Leonard Cottrell", "1968", "Rocco", "São Paulo", "5", "Emprestado")
catalogo_biblioteca.addLivro("Xadrez", "Julio Cesar de Mello e Souza", "1943", "Zahar", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Xingu e Outros Contos", "José de Alencar", "1870", "Martin Claret", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Xingu: A Saga", "Francisco de Assis", "2002", "Record", "Rio de Janeiro", "4", "Emprestado")
catalogo_biblioteca.addLivro("Xingu: Aventuras Brasileiras", "Bernardo Carvalho", "2001", "Companhia das Letras", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("X-Men: O Filme", "Stan Lee", "2000", "Panini", "São Paulo", "3", "Disponível")
catalogo_biblioteca.addLivro("Xingu e o Mundo", "Luiz Puntel", "1999", "Rocco", "Rio de Janeiro", "4", "Emprestado")
catalogo_biblioteca.addLivro("Xenofobia e Cultura", "Celso Lafer", "1985", "Martins Fontes", "São Paulo", "4", "Disponível")

# ======================= Y =======================
catalogo_biblioteca.addLivro("Yago: O Trágico", "William Shakespeare", "1601", "Martin Claret", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Y: O Último Homem", "Brian K. Vaughan", "2002", "Panini", "São Paulo", "5", "Emprestado")
catalogo_biblioteca.addLivro("Yes, Chef", "Marcus Samuelsson", "2012", "Rocco", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Yoga para Leigos", "Georg Feuerstein", "1998", "Sextante", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Yucatán", "James Michener", "1985", "Companhia das Letras", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Yoni: A Energia Feminina", "Anodea Judith", "1999", "Rocco", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("You Are a Badass", "Jen Sincero", "2013", "Editora Gente", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Yes Man", "Danny Wallace", "2005", "Record", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Yin e Yang", "Mantak Chia", "1990", "Sextante", "São Paulo", "5", "Emprestado")
catalogo_biblioteca.addLivro("Yakuza: Uma História", "Jake Adelstein", "2003", "Zahar", "Rio de Janeiro", "4", "Disponível")

# ======================= Z =======================
catalogo_biblioteca.addLivro("Zorro", "Isabel Allende", "2005", "Rocco", "Rio de Janeiro", "5", "Disponível")
catalogo_biblioteca.addLivro("Zen e a Arte da Manutenção de Motocicletas", "Robert M. Pirsig", "1974", "Martin Claret", "São Paulo", "4", "Disponível")
catalogo_biblioteca.addLivro("Zona Morta", "Stephen King", "1979", "Suma de Letras", "Rio de Janeiro", "3", "Emprestado")
catalogo_biblioteca.addLivro("Zumbis: A História", "Max Brooks", "2006", "Intrínseca", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Zahir", "Paulo Coelho", "2005", "Paralela", "São Paulo", "5", "Disponível")
catalogo_biblioteca.addLivro("Zumbi", "José de Alencar", "1895", "Martin Claret", "São Paulo", "3", "Emprestado")
catalogo_biblioteca.addLivro("Zé do Caixão", "José Mojica Marins", "1993", "Rocco", "Rio de Janeiro", "4", "Disponível")
catalogo_biblioteca.addLivro("Zumbis no Brasil", "Fábio Yabu", "2010", "Record", "Rio de Janeiro", "3", "Disponível")
catalogo_biblioteca.addLivro("Zangado", "Rick Riordan", "2008", "Intrínseca", "Rio de Janeiro", "5", "Emprestado")
catalogo_biblioteca.addLivro("Zuleica", "José de Alencar", "1880", "Martins Fontes", "São Paulo", "4", "Disponível")


catalogo_biblioteca.bus()